version: '3'

services:
  app:
    environment:
      - AUTH=SAML_MOCK
      - EDW_USER
      - EDW_PASSWORD
      - RESTCLIENTS_SWS_OAUTH_BEARER
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./retention_data_pipeline:/app/retention_data_pipeline
    ports:
      - "8000:8000"
